HHMVC0522/Areas/Admin/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using DTO;
using PagedList;

namespace UI.Areas.Admin.Controllers
{
    public class MealController : Controller
    {
        // GET: Admin/Meal
        public ActionResult List()
        {

            MealBLL bll = new MealBLL();
            List<MealDetailDTO> dtos = new List<MealDetailDTO>();
            dtos = bll.GetOnlyMeals();
            
            return View(dtos);
        }
        public ActionResult CreateMeal()
        {
            MealDetailDTO mealDetailDTO = new MealDetailDTO();
            return View(mealDetailDTO);
        }
        [HttpPost]
        public ActionResult CreateMeal(MealDetailDTO mealDetailDTO)
        {
            if (mealDetailDTO.MealOptionUpLoadImage != null)
            {
                Bitmap image = new Bitmap(mealDetailDTO.MealOptionUpLoadImage.InputStream);
                Bitmap resizedImage = new Bitmap(image, 250, 250);
                string uniqueNumber = Guid.NewGuid().ToString();
                string fileName = uniqueNumber + mealDetailDTO.MealOptionUpLoadImage.FileName;
                resizedImage.Save(Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + fileName));
                mealDetailDTO.MealOptionImage = fileName;
            }
            else
            {
                mealDetailDTO.MealOptionImage = "mealDefault.jpg";
            }
            MealBLL bll = new MealBLL();
            bll.Add(mealDetailDTO);
            return RedirectToAction("List");

        }
        public ActionResult CreateMealWithTags()
        {
            TagCategoryDetailBLL tagBll = new TagCategoryDetailBLL();
            MealDetailDTO mealDetailDTO = new MealDetailDTO();
            //mealDetailDTO.Tags = tagBll.GetTagForAddMeal();
            mealDetailDTO.DTags = tagBll.getDTags();
            return View(mealDetailDTO);
        }
        [HttpPost]
        public ActionResult CreateMealWithTags(MealDetailDTO mealDetailDTO,List<string> tags)
        {
            if (ModelState.IsValid)
            {
                if (mealDetailDTO.MealOptionUpLoadImage != null)
                {
                    Bitmap image = new Bitmap(mealDetailDTO.MealOptionUpLoadImage.InputStream);
                    Bitmap resizedImage = new Bitmap(image, 250, 250);
                    string uniqueNumber = Guid.NewGuid().ToString();
                    string fileName = uniqueNumber + mealDetailDTO.MealOptionUpLoadImage.FileName;
                    resizedImage.Save(Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + fileName));
                    mealDetailDTO.MealOptionImage = fileName;
                }
                else
                {
                    mealDetailDTO.MealOptionImage = "mealDefault.jpg";
                }
                MealBLL bll = new MealBLL();
                int mealID = bll.Add(mealDetailDTO);
                TagCategoryDetailBLL tagCategoryDetailBLL = new TagCategoryDetailBLL();
                tagCategoryDetailBLL.AddMealTags(mealID, tags);
                return RedirectToAction("List");
            }
            else
            {
                TagCategoryDetailBLL tagBll = new TagCategoryDetailBLL();
                //mealDetailDTO.Tags = tagBll.GetTagForAddMeal();
                mealDetailDTO.DTags = tagBll.getDTags();
                return View(mealDetailDTO);
            }

        }

        public ActionResult Delete(int id)
        {
            MealBLL bll = new MealBLL();
            bll.DeleteMeal(id);
            return RedirectToAction("List");
        }

        public ActionResult HiddenMeal(int ID)
        {
            MealBLL bll = new MealBLL();
            bll.HiddenMeal(ID);
            return RedirectToAction("List");
        }
        public ActionResult DisplayMeal(int ID)
        {
            MealBLL bll = new MealBLL();
            bll.DisplayMeal(ID);
            return RedirectToAction("List");
        }

        public ActionResult Update(int id)
        {
            MealBLL mealbll = new MealBLL();
            TagCategoryDetailBLL tagCategoryDetailBLL = new TagCategoryDetailBLL();
            MealDetailDTO dto = new MealDetailDTO();
            dto = mealbll.GetMeals(id);
            return View(dto);
        }
        [HttpPost]
        public ActionResult Update(MealDetailDTO dto)
        {
            if (dto.MealOptionUpLoadImage != null)
            {
                Bitmap image = new Bitmap(dto.MealOptionUpLoadImage.InputStream);
                Bitmap resizedImage = new Bitmap(image, 250, 250);
                string uniqueNumber = Guid.NewGuid().ToString();
                string fileName = uniqueNumber + dto.MealOptionUpLoadImage.FileName;
                resizedImage.Save(Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + fileName));
                dto.MealOptionImage = fileName;
            }
            MealBLL bll = new MealBLL();
            
            string oldImagePass = bll.UpdateMeal(dto);
            string imageFullPath = Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + oldImagePass);
            if (System.IO.File.Exists(imageFullPath))
            {
                System.IO.File.Delete(imageFullPath);
            }
            return RedirectToAction("List");
        }
        public ActionResult UpdateWithTags(int id)
        {
            MealBLL mealbll = new MealBLL();
            MealDetailDTO dto = new MealDetailDTO();
            TagCategoryDetailBLL tagBll = new TagCategoryDetailBLL();
            //mealDetailDTO.Tags = tagBll.GetTagForAddMeal();
            dto = mealbll.GetMealWithTags(id);
            dto.DTags = tagBll.getDTags();
            return View(dto);
        }
        [HttpPost]
        public ActionResult UpdateWithTags(MealDetailDTO dto, string[] tags)
        {
            if (dto.MealOptionUpLoadImage != null)
            {
                Bitmap image = new Bitmap(dto.MealOptionUpLoadImage.InputStream);
                Bitmap resizedImage = new Bitmap(image, 250, 250);
                string uniqueNumber = Guid.NewGuid().ToString();
                string fileName = uniqueNumber + dto.MealOptionUpLoadImage.FileName;
                resizedImage.Save(Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + fileName));
                dto.MealOptionImage = fileName;
            }
            MealBLL bll = new MealBLL();
            TagCategoryDetailBLL tagBll = new TagCategoryDetailBLL();
            tagBll.UpdateMealTags(dto.ID, tags);
            string oldImagePass = bll.UpdateMeal(dto);
            string imageFullPath = Server.MapPath("~/Areas/Admin/Content/MealOptionImages/" + oldImagePass);
            if (dto.MealOptionUpLoadImage != null)
            {
                if (System.IO.File.Exists(imageFullPath))
                {
                    System.IO.File.Delete(imageFullPath);
                }
            }
            
            return RedirectToAction("List");
        }


        public ActionResult ListTest()
        {

            MealBLL bll = new MealBLL();
            List<MealDetailDTO> dtos = new List<MealDetailDTO>();
            dtos = bll.GetOnlyMeals();

            return View(dtos);
        }

        public ActionResult PageTest(int page=1)//預設第一頁
        {
            int currentPage = page < 1 ? 1 : page;

            MealBLL bll = new MealBLL();
            List<MealDetailDTO> dtos = new List<MealDetailDTO>();
            dtos = bll.GetOnlyMeals();

            var pagedResukt = dtos.ToPagedList(currentPage, 10);//回傳客戶端請求的頁數及筆數


            return View(pagedResukt);
        }
        public bool checkMaelName(string userInput)
        {
            MealBLL bll = new MealBLL();
            bool check = bll.checkMealName(userInput);
            return check;
        }
    }
}

HHMVC0522/Areas/Admin/Views/Meal/CreateMeal.cshtml
@model DTO.MealDetailDTO

@{
    ViewBag.Title = "Creat";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h2>新增餐點</h2>


@using (Html.BeginForm("CreateMeal", "Meal", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>餐點名稱</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>卡路里</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>餐點圖片</label>
            <input type="file" name="MealOptionUpLoadImage" id="progressbarTWInput" accept="image/gif, image/jpeg, image/png" />
        </div>
        <div>
            <p>
                預覽圖:
            </p>
            <img id="preview_progressbarTW_img" src="#" />
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.UnitName, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>餐點份量</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.TagName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TagName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TagName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TagImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TagImage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TagImage, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.NutrientID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NutrientID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NutrientID, "", new { @class = "text-danger" })
                </div>
            </div>*@

    <div class="form-group">
        @* @Html.LabelFor(model => model.Fat, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>脂肪</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Fat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @* @Html.LabelFor(model => model.Protein, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>蛋白質</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Protein, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Protein, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @*@Html.LabelFor(model => model.Carbs, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>碳水化合物</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Carbs, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Carbs, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @* @Html.LabelFor(model => model.Sugar, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>糖</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sugar, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sugar, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @* @Html.LabelFor(model => model.VitA, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>維生素A</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.VitA, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VitA, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @* @Html.LabelFor(model => model.VitB, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>維生素B</label>
        <div class="col-md-10">
            @Html.EditorFor(model => model.VitB, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.VitB, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.VitC, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>維生素C</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VitC, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VitC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.VitD, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>維生素D</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VitD, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VitD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.VitE, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>維生素E</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VitE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VitE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.Na, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>鈉</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Na, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Na, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.Potassium, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>鉀</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Potassium, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Potassium, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @* @Html.LabelFor(model => model.Calcium, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>鈣</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calcium, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calcium, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Icon, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label>鐵</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Icon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Icon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增餐點" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回餐點列表", "List")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
<script>

    $("#progressbarTWInput").change(function () {

        readURL(this);

    });
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#preview_progressbarTW_img").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

HHMVC0522/Areas/Admin/Views/Meal/ListTest.cshtml
@using PagedList;
@using PagedList.Mvc;
@using DTO;
@using BLL;

@model IEnumerable<DTO.MealDetailDTO>

@{
    ViewBag.Title = "ListTest";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
}

<section class="content-header">
    <h1>所有餐點</h1>
    <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>後臺頁面</a></li>
        <li class="breadcrumb-item"><a>飲食</a></li>
        <li class="breadcrumb-item active"><a>所有餐點</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Meal/CreateMeal'">新增餐點</button>
</div>

<div class="card">
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>餐點ID</th>
                    <th>名稱</th>
                    <th>餐點圖片</th>
                    <th>餐點標籤</th>
                    <th>修改</th>
                    <th>刪除</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr id="a_@item.ID">
                        <td>@item.ID</td>
                        <td>@item.Name</td>
                        <td>
                            <img src="~/Areas/Admin/Content/MealOptionImages/@item.MealOptionImage" width="50" height="50" />
                        </td>
                        <td>
                            @item.TagStringList
                        </td>
                        <td align="center" valign="middle">
                            <a href="/Admin/Meal/Update/@item.ID">
                                <img src="~/Areas/Admin/Content/icon/update-icon.png" />
                            </a>
                        </td>
                        <td align="center" valign="middle">
                            <a href="#">
                                <img src="~/Areas/Admin/Content/icon/close-icon.png" onclick="AskQuestion('/Admin/Meal/Delete/', @item.ID)" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>餐點ID</th>
                    <th>名稱</th>
                    <th>餐點圖片</th>
                    <th>餐點標籤</th>
                    <th>修改</th>
                    <th>刪除</th>
                </tr>
            </tfoot>
        </table>
    </div>
    @Html.Partial("~/Areas/Admin/Views/Shared/ModalMessage.cshtml")
    <!-- /.card-body -->
</div>
<script src="~/Areas/Admin/Content/JS/DeleteRecord.js"></script>
<!-- /.card -->

HHMVC0522/Areas/Admin/Views/Meal/Update.cshtml
@model DTO.MealDetailDTO

@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}


<section class="content-header">
    <h1>更新餐點</h1>
    <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>後臺頁面</a></li>
        <li class="breadcrumb-item"><a>餐點</a></li>
        <li class="breadcrumb-item active"><a>更新餐點</a></li>
    </ol>
</section>
<br />

@using (Html.BeginForm("Update", "Meal", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Calories, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @* @Html.LabelFor(model => model.MealOptionImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>現在圖片：</label>
        <div class="col-md-10">
            <img src="~/Areas/Admin/Content/MealOptionImages/@Model.MealOptionImage" name="NowImage" />
            @*@Html.EditorFor(model => model.MealOptionImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MealOptionImage, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        @* @Html.LabelFor(model => model.MealOptionImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
        <label>更新圖片：</label>
        <input type="file" name="MealOptionUpLoadImage" id="progressbarTWInput" accept="image/gif, image/jpeg, image/png" />
        <div class="col-md-10">
            <img id="preview_progressbarTW_img" src="#" />
            @*@Html.EditorFor(model => model.MealOptionImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MealOptionImage, "", new { @class = "text-danger" })*@
        </div>
    </div>
   

    <div class="form-group">
        @Html.LabelFor(model => model.UnitName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="儲存變更" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
<script>

    $("#progressbarTWInput").change(function () {

        readURL(this);

    });
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#preview_progressbarTW_img").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            console.log()
        }
    }

</script>

HHMVC0522/Areas/Admin/Views/Meal/UpdateWithTags.cshtml
@using System.Collections

@model DTO.MealDetailDTO

@{
    ViewBag.Title = "UpdateWithTags";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">
    <h1>更新餐點</h1>
    <ol class="breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>後臺頁面</a></li>
        <li class="breadcrumb-item"><a>餐點</a></li>
        <li class="breadcrumb-item active"><a>更新餐點</a></li>
    </ol>
</section>
<br />

<div style="margin-left:10px">
    @using (Html.BeginForm("UpdateWithTags", "Meal", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group col-4">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @id = "Name" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @id = "Name" })
                    </div>
                </div>
                <div>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-4">
                    <label>卡路里</label>
                    <div>
                        @Html.EditorFor(model => model.Calories, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Calories, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-4">
                    <label>份量</label>
                    <div>
                        @Html.EditorFor(model => model.UnitName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class=" col-4"></div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label>現在圖片：</label>
                    <div class="col-md-10">
                        <img src="~/Areas/Admin/Content/MealOptionImages/@Model.MealOptionImage" name="NowImage" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label>更新圖片：</label>
                <input type="file" name="MealOptionUpLoadImage" id="progressbarTWInput" accept="image/gif, image/jpeg, image/png" />
                <div class="col-md-10">
                    <img id="preview_progressbarTW_img" src="#" />
                </div>
            </div>
            <div class="form-group">
                <label>標籤：</label>
                <div class="col-md-10">
                    <div class="checkbox">
                        <div class="row col-5">
                            @{
                                string[] TagStringArray = Model.TagStringListArray;
                                int count = 0;
                                foreach (var item in Model.DTags)
                                {

                                    count = count + 1;
                                    if (count == 5)
                                    {
                                        <br />
                                        count = 0;
                                    }
                                    bool checkTags = ((IList)TagStringArray).Contains(item.Value);
                                    if (checkTags)
                                    {
                                        <div class="col-3">
                                            <label>
                                                <input type="checkbox"
                                                       name="tags"
                                                       id="@item.Key"
                                                       value="@item.Key"
                                                       checked="true" />@item.Value
                                                </label>
                                            </div>
                                        }
                                        else
                                        {
                                            <div class="col-3">
                                                <label>
                                                    <input type="checkbox"
                                                           name="tags"
                                                           id="@item.Key"
                                                           value="@item.Key" />@item.Value
                                                    </label>
                                                </div>
                                            }
                                        }
                            }
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="儲存變更" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>
@section Scripts{
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Areas/Admin/Content/JS/jquery.min.js"></script>
<script>

    $("#progressbarTWInput").change(function () {

        readURL(this);

    });
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $("#preview_progressbarTW_img").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            console.log()
        }
    }
</script>
}