HHMVC0522/ViewModels/RegisterProgramViewModel.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.ViewModels
{
    public class RegisterProgramViewModel
    {

        WeightLogBLL wlBLL = new WeightLogBLL();
        ProgramBLL pBLL = new ProgramBLL();
        private int _MemberID;
        public RegisterProgramViewModel(int memberID) {

            _MemberID = memberID;
        }


        public int MemberID { get { return _MemberID; } }

        public IEnumerable<SelectListItem> ActivityLevelsSelectListItem { get { return ActivityLevelBLL.GetActivityLevelsForDropDown(); } }


        public double SuccessRate { get { return pBLL.GetSuccessRate(); } }

        public double MemberLatestWeight
        {
            get
            {
                double weight = 0;
                WeightLog weightRecord = wlBLL.GetLatestWeightByMemberID(_MemberID);
                if (weightRecord != null)
                {
                    weight = weightRecord.Weight;
                }
                return weight;
            }
        }
    }


    }

HHMVC0522/Controllers/HHProgramsController.cs
using BLL;
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.ViewModels;

namespace UI.Controllers
{
    public class HHProgramsController : Controller
    {
        // GET: HHPrograms

        ProgramBLL pBLL = new ProgramBLL();
      
        public ActionResult RegisterProgram()
        {

            int memberID = 17; 
            if (Session["ID"] != null)
            {
                memberID = (int)Session["ID"];
            }
            ProgramPageViewModel model = new ProgramPageViewModel(memberID);  //used?


            return View(model);

        }
       
        


    }
}

HHMVC0522/Views/HHPrograms/RegisterProgram.cshtml
@model UI.ViewModels.ProgramPageViewModel



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/HomeLayout2.cshtml";
}
@section Styles{
    @*<link href="~/Content/css/dietAddMeal.css" rel="stylesheet" />
        <link href="~/Content/css/stylesPlay.css" rel="stylesheet" />*@

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <style>
    </style>
}

<header style="background-color: #fff0f0; width: 100%; padding-right: 0px " class="pt-5 pb-1 m-0 col-12">
    <div class="row" style="width: 100%; padding-right: 20px">

        <div class="col-3 col-sm-3 col-lg-2 p-2 p-0" style="text-align:center">
            <a href="~/Home2/Index"><img src="~/Areas/Admin/Content/tempimage/hLogoRed.jpg" style="max-width:90px;width:100%"></a>
        </div>
        <div class="col-8 col-sm-7 col-lg-8 p-1 align-self-center">
            <h2 style="font-size:1.8em"><i class="fas fa-pen-nib" style="width:30px"></i> 減脂計畫</h2>
        </div>

    </div>
</header><header id="header" class="m-0 p-0"></header>




         <section class="pt-2 pb-5">


             <div id="mainProgramContent" class="col-8 justify-content-center" style="margin:0 auto; margin-top:2em">
                 @{if (Model.HasActiveProgram)
                     {
                         @Html.Partial("_ShowProgramPartial", Model.ProgramView)
                     }
                     else
                     {
                         @Html.Partial("_RegisterProgramPartial", Model.RegisterView)
                     }
                 }
             </div>
         </section>

    <!-- Modal -->
    <div class="modal fade" id="ProgramCalculating" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="programPending">計畫審核中...</h3>

                </div>
                <div class="modal-body" style="display:flex;justify-content:center">
                    <img id="pendingImg" style="max-width: 100%; max-height: 100%; " src="~/Content/Images/loadingDots.gif" />
                </div>
                <div class="modal-footer row">
                    <div class="col-12">
                        <p id="pendingReminder"></p>
                    </div>
                    <div class="col-12">
                        <input type="button" id="closeModal" value="確定" class="btn btn-default fit" />
                    </div>
                </div>
            </div>
        </div>
    </div>


    @section Scripts{


        @*-----------------Ttool built them used?--------*@
        @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>*@
        <!--<script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/Content/js/chart.min.js"></script>-->   @*FOR WATERLOG*@




        @*<script src="https://code.jquery.com/jquery-1.12.4.js"></script>*@
        @*<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>*@
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>   FOR WATERLOG


        @*----------------------------------*@

    <script>
        //closeModal
        $("#closeModal").click(() => {
            $("#ProgramCalculating").modal("hide")
            $("#programPending").text("計畫審核中...")

            $("#pendingImg").attr("src", "../Content/Images/loadingDots.gif")

            $("#pendingReminder").text("")

        });


    $(function BindingJSevents() {
        $("#ProName").on("click", (e) => {
            console.log($(e.currentTarget))
            $(e.currentTarget).val("我一定要變瘦追到小新!")

        })
        $(".datepicker").datepicker({
            minDate: "+14",
            maxDate: "+180",
        });

        $("#btnSendRegister").on("click", (e) => {
            e.preventDefault()

            $("#ProgramCalculating").modal('show')
            const formData = new FormData(document.RegisterProgramForm)

            fetch('@Url.Action("RegisterProgram", "HHApi_Program")', {
                method: "POST",
                body: formData
            }).then(response => response.text()).then(data => {
                $("#mainProgramContent").html(data)
                if ($("#hiddenHasProgram").val() == "true") {
                    $("#programPending").text("恭喜你! 減脂計畫註冊成功 加油!")
                    $("#pendingImg").attr("src", "../Content/Images/ProgramImages/goodLuckImg.jpg")
                    $("#pendingReminder").text("提醒您, 我們也為您新增了一筆起始體重紀錄以及更新您的活動量紀錄 祝您好運!")
                } else {
                    $("#programPending").text("註冊失敗... 這樣減脂太不健康啦!")
                    $("#pendingImg").attr("src", "../Content/Images/ProgramImages/sorriImg.jpg")

                }

                BindingJSevents()

            })
        })

        $("#btnTerminateProgram").on("click",() => {

            if (confirm(`只剩${$("#restDays").text()}天 ${$("#currProgramName").text()} 計畫就成功了..確定要終止嗎?`))
            {

                fetch('@Url.Action("TerminateProgram", "HHApi_Program")?programId=' + $("#currProgramId").val(), {
                    method: "GET",
                 }).then(response => response.text()).then(data => {
                     $("#mainProgramContent").html(data)
                     BindingJSevents()

                 })
            }

        })

    })



        </script>


    }

HHMVC0522/Views/HHPrograms/ShowActiveProgram.cshtml
@model DAL.Program

@{
    ViewBag.Title = "ShowActiveProgram";
}

<h2>ShowActiveProgram</h2>

<div>
    <h4>Program</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MemberID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TargetWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TargetWeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivityLevelID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivityLevelID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InitialWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InitialWeight)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("終止計畫", "Delete", "HHPrograms", new { programID = Model.ID }, new { OnClick = "return confirm('Are you sure to delete?')", @class = "btn btn-danger" })  |
    @Html.ActionLink("Back to List", "Index")
</p>